#stage1
FROM node:16-alpine as build

WORKDIR /app/client

COPY package* .

RUN  npm install --silent

COPY . .

RUN npm run build

#stage2

FROM nginx:stable-alpine

COPY .env.production .

COPY --from=build /app/client/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]

