#stage1
FROM node:16-alpine as build

WORKDIR /app/client

COPY package* .

RUN  npm install --silent

COPY . .

RUN npm run build

#stage2
FROM node:16-alpine

WORKDIR  /app/client

ENV NODE_ENV=production

COPY .env.development .

COPY --from=build /app/client/dist dist

CMD ["npx", "serve", "-s", "dist"]